# Generated by Django 2.1.15 on 2021-02-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Consumables', 'Consumables')], max_length=15),
        ),
    ]
