# Generated by Django 2.1.15 on 2021-02-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
        migrations.AlterField(
            model_name='stock',
            name='part_no',
            field=models.CharField(max_length=15),
        ),
    ]
