# Generated by Django 2.1.15 on 2021-02-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='HSN_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='issue_units',
            field=models.CharField(choices=[('Kgs', 'Kgs'), ('Nos', 'Nos'), ('Ltrs', 'Ltrs')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='item_no',
            field=models.CharField(default=900000000, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='part_no',
            field=models.CharField(default=900000000, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='receive_units',
            field=models.CharField(choices=[('Kgs', 'Kgs'), ('Nos', 'Nos'), ('Ltrs', 'Ltrs')], default='Nos', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_units',
            field=models.CharField(choices=[('Kgs', 'Kgs'), ('Nos', 'Nos'), ('Ltrs', 'Ltrs')], default='Nos', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='sub_category',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability')], default='Assets', max_length=10),
            preserve_default=False,
        ),
    ]
