# Generated by Django 2.1.15 on 2021-02-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210217_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='issue_units',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='receive_units',
        ),
    ]
