# Generated by Django 2.1.15 on 2021-02-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210224_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='units',
            field=models.CharField(choices=[('Kgs', 'Kgs'), ('Nos', 'Nos'), ('Ltrs', 'Ltrs'), ('Mtrs', 'Mtrs')], max_length=5),
        ),
    ]
