# Generated by Django 2.1.15 on 2021-02-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210217_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='updated_by',
            field=models.CharField(default='YVS', max_length=50),
            preserve_default=False,
        ),
    ]
