# Generated by Django 2.1.15 on 2021-02-25 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20210225_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='updated_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
