# Generated by Django 2.1.15 on 2021-02-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210210_1351'),
        ('stocks', '0008_auto_20210210_1256'),
    ]

    operations = [
    ]
